### ISSUE TITLE
Compile to ES modules

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#1004]
Right now, CosmJS produces CommonJS builds. This works well for all versions of Node.js as well as bundlers like Webpack in order to bundle for the web.

As mentioned in https://vuejsdevelopers.com/2019/02/04/vue-es-module-browser-build/ ("What benefit is there of using Vue as an ES module?"), there is little obvious benefit for switching from CommonJS to ESM since the consumers are either node.js apps or bundlers. However, there is hope that ESM helps optimizing bundle size through tree shaking because ESM can better do static analysis on what is used and what is not (https://webpack.js.org/guides/tree-shaking/). In #904 you see that right now web apps include a lot of unused code that is only needed for key storage.

Other libraries use bundlers to bundle ES modules for the web. This is not desired here as we don't have a single entry point and do not want to decide for that user what should be included in such a bundle.

**Do we need CommonJS+ESM hybrid builds?**

- Node.js 12 does not support ESM natively without feature flags. But this version reaches EOL at 2022-04-30.
- Webpack support ESM inputs since version 2 (["The webpack 2 release came with built-in support for ES2015 modules (alias harmony modules)"](https://webpack.js.org/guides/tree-shaking/))

**Does this reduce bundle size**

- [ ] Test in a next.js project with [the analyze plugin](https://github.com/cosmos/cosmjs/issues/904#issuecomment-1018681955)

**Testing**

- [x] **Jasmine supports ESM** build testing (see https://github.com/jasmine/jasmine-npm/issues/170)
- [ ] **JSON test vectors cannot be used easily in tests**. `const bip39Vectors = require("./src/testdata/bip39.json");` works and TS transpiles `import bip39Vectors from "./testdata/bip39.json";` to `const bip39_json_1 = __importDefault(require("./testdata/bip39.json"))`. But an untranspiled `import bip39Vectors from "./testdata/bip39.json";` output is not working. See https://nodejs.org/api/esm.html#no-json-module-loading and https://nodejs.org/api/esm.html#json-modules. A workaround for tests is:
  ```ts
  import { createRequire } from "module";
  const require = createRequire(import.meta.url);
  const bip39Vectors = require("../src/testdata/bip39.json");
  ```
  but this does not work in Webpack/Karma.
- [ ] **File extensions must me used**. `import { EnglishMnemonic } from "./englishmnemonic.js";` must be used for a local file instead of `import { EnglishMnemonic } from "./englishmnemonic";`. [TS will not do this for us](https://github.com/microsoft/TypeScript/issues/16577#issuecomment-754941937).

**Comment by webmaster128** [comment]
> Didn't Node.js [v17.1](https://nodejs.org/en/blog/release/v17.1.0) and [v16.14](https://nodejs.org/en/blog/release/v16.14.0) add support for `import data from './data.json' assert { type: 'json' };` and `await import('./data.json', { assert: { type: 'json' } })`.

It seems like we have support for JSON imports in modern browsers and Node 20: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import/with#browser_compatibility

**Comment by webmaster128** [comment]
Also: can't tsc output a single file instead of many?

**Comment by dynst** [comment]
Webpack is the legacy choice these days, its modern ESM support is very new, immature, and gated behind the `experiments` boolean.

https://webpack.js.org/configuration/output/#type-modern-module

I think Vite is the choice people gravitate towards now. It uses `rollup` and `esbuild`.

https://vite.dev/config/build-options.html#build-lib

I think Rollup can still produce separate files, but will completely rewrite imports to add `.js or `/index.js` for you.

https://rollupjs.org/configuration-options/#output-preservemodules

> Also: can't tsc output a single file instead of many?

True, didn't think of that. But Rollup does things tsc doesn't.

**Comment by dynst** [comment]
Are these not good reasons `tsc` isn't ideal?

https://github.com/microsoft/TypeScript/issues/49462
https://github.com/microsoft/TypeScript/issues/42151


Rewriting imports would be tedious, but then even if that's done, to make CJS and ESM coexist, you need to give them different file extensions like `.cjs` and `.mjs` but `tsc` just doesn't support giving customizing file extensions for its output. At all.

But then Node 20 is the minimum version now and supports CommonJS users `require(esm)`, is there actually a technical reason to keep CJS output at this point?

**Comment by dynst** [comment]
Definitely possible. His projects all use explicit file extensions https://github.com/paulmillr/noble-curves/commit/fa50a114a8241982b4e8c2fa40e3bcc77c3766ce

esbuild needs a plugin to handle omitted file extensions https://github.com/evanw/esbuild/issues/2435

A lot of other library authors complain about the lack of being able to replicate rollup's `preserveModules` option.

https://github.com/evanw/esbuild/issues/708#issuecomment-1528863083

**Comment by webmaster128** [comment]
What do you think about the approach described here? https://cmdcolin.github.io/posts/2025-01-12-pureesm Does it allow us to get an ESM package built by just tsc? `rewriteRelativeImportExtensions` compiles all .ts imports to `.js`

**Comment by dynst** [comment]
That's not what it does, it rewrites *extensions* that already exist. It definitely can't rewrite directory imports, or add extensions to extensionless imports.

https://www.typescriptlang.org/tsconfig/rewriteRelativeImportExtensions.html

> Rewrite .ts, .tsx, .mts, and .cts file extensions in relative import paths to their JavaScript equivalent in output files.

For code bases that use `.ts` like https://github.com/paulmillr/noble-curves/commit/fa50a114a8241982b4e8c2fa40e3bcc77c3766ce
