### ISSUE TITLE
Summer 2022 roadmap

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#1105]
High level roadmap of bigger topics we want to get done over the course of Q2/Q3 (unsoted):

- [ ] Implement Sign mode textual (Cosmos SDK 0.47 or later)
- [ ] Replace libsodium dependency (#1031)
- [ ] Import arbitrary messages from protobuf JSON (e.g. for multisig tool) (https://github.com/cosmos/cosmjs/pull/1083)
- [ ] Feegrant support (Cosmos SDK 0.43) (https://github.com/cosmos/cosmjs/pull/1159)
- [ ] Tips support (Cosmos SDK 0.46)
- [ ] Figure out if/when we can move from Tendermint RPC to gRPC/grpw-web (#885)
- [ ] Basic support for groups/gov1 (probably just type generation, maybe Amino JSON) (Cosmos SDK 0.46)

**Comment by puneet2019** [comment]
saw [cosmos-sdk v45.2](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.45.2), 
> Register [EIP191](https://eips.ethereum.org/EIPS/eip-191) as an available SignMode for chains to use. Please note that in v0.45.2, the Cosmos SDK does not support EIP-191 out of the box. But if your chain wants to integrate EIP-191, it's possible to do so by passing a TxConfig with your own sign mode handler which implements EIP-191, using the new provided authtx.NewTxConfigWithHandler function.

have not looked at it yet, but is this going to be `sign mode textual`?

**Comment by webmaster128** [comment]
> have not looked at it yet, but is this going to be `sign mode textual`?

Those are different things. EIP191 is Ethereum (Evmos?) specific. See https://github.com/cosmos/cosmos-sdk/pull/11533

**Comment by puneet2019** [comment]
oh! I see, one more addition.

**Comment by sunnya97** [comment]
I have most of the code for eip191 support done in this branch:   https://github.com/osmosis-labs/cosmjs/tree/sunny/eip191

I can spend some time getting it ready for merge

**Comment by liangping** [comment]
@webmaster128 Would you like to help us adding `ethsecp256k1` to Cosmjs?

Can you add me? My Discord: Ping#5079

**Comment by pyramation** [comment]
If I update dates/durations working with the plugin as planned to work with cosmjs-types, maybe we can test out some of the group and gov modules' amino messages: https://github.com/osmosis-labs/telescope/blob/846fa64ac0934d6490a1d0afe5f35ae894f8c8b8/packages/osmojs/src/proto/cosmos/group/v1/tx.amino.ts

**Comment by nooomski** [comment]
@pyramation would love if we could use telescope to accelerate the type generation for gov/groups when v0.46 is released ❤️

**Comment by pyramation** [comment]
> @pyramation would love if we could use telescope to accelerate the type generation for gov/groups when v0.46 is released ❤️

100% — this is exactly the use case. I think we can save a lot of developer hours if we can use telescope. I may have a few questions about some encodings, but generally telescope should be pluggable for us to accomplish this in a replicable way.

**Comment by webmaster128** [comment]
Closing as the list above got outdated. The tickets are still open. But more important things came up, the funding situation is unclear and summer is over.
