### ISSUE TITLE
Create CosmosClient/SigningCosmosClient in @cosmjs/stargate

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#272]
We need higher level clients `CosmosClient`/`SigningCosmosClient` in @cosmjs/stargate that have the same interface as in @cosmjs/launchpad to make it easy to upgrade. They should use tendermint-rpc and https://github.com/CosmWasm/cosmjs/issues/212 under the hood.

**read-only**:

- [x] Add `StargateClient`
- [x] Add `getChainId` (directly via Tendermint RPC): #362
- [x] Add `getHeight` (directly via Tendermint RPC): #362
- [x] Add `getSequence`
- [x] Add `getAccount` (address, pubKey, accountNumber, sequence but no balances): #361
- [x] Add `getBalance`/`getAllBalancesUnverified`
- [x] Add `getBlock` #375
- [x] Add `searchTx` #380 
- [x] Add `broadcastTx` (directly via Tendermint RPC) #373 
- [x] Add `txsQuery` (directly via Tendermint RPC) #380 

**read/write**:

Depends on: #212

- [ ] Add `SigningStargateClient`
- [ ] Add `sendTokens`
- [ ] Add `signAndBroadcast`

**Comment by webmaster128** [comment]
I started using `StargateClient` (and `SigningStargateClient`) as alternatives to CosmosClient/SigningCosmosClient in order to avoid unnecessary naming collisions in the project. So the description above is a bit outdated.
