### ISSUE TITLE
Copy shared functionality from @cosmjs/launchpad

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#657]
We now see CosmJS based Stargate clients using imports like this:

```ts
import { coins, GasPrice } from "@cosmjs/launchpad";
import { SigningStargateClient } from "@cosmjs/stargate";
import { DirectSecp256k1HdWallet } from "@cosmjs/proto-signing";
```

But ideally, `@cosmjs/stargate` was entirely independent of `@cosmjs/launchpad`. Especially users of stargate should not be required to import launchpad packages to keep caller code clean. In order to avoid duplicating functionality, I suggest pulling out a shared package `@cosmjs/cosmos`. What I think should be in there is:

- [x] `coin`/`coins`/`Coin`/`parseCoins` (#721)
- [x] `GasPrice`/`CosmosFeeTable`/`GasLimits`/`buildFeeTable`
- [x] fee things?
- [x] `makeCosmoshubPath`
- [x] pubkey and address things (#719)
- [x] `AccountData` for `OfflineDirectSigner`
- [x] logs module (or parts of it) (#721)

**Comment by willclarktech** [comment]
How confident are we that these types/functions will be applicable unchanged to whatever follows Stargate?

What about simply re-exporting the `@cosmjs/launchpad` code from `@cosmjs/stargate` so that consumers of the latter don't need to know anything about the former but we also don't duplicate functionality? Then if/when we drop launchpad support we can just copy the code across, but this is an internal change that doesn't affect the `@cosmjs/stargate` API.

**Comment by webmaster128** [comment]
Right, very good idea. Let's copy them right away and work towards `@cosmjs/stargate` being independent of `@cosmjs/launchpad`.

**Comment by webmaster128** [comment]
Most likely we cannot complete this as long as there is amino signing in stargate. But we can do important steps in the right direction.

**Comment by willclarktech** [comment]
@webmaster128 Good to close?
